import { Step } from "./type";

const steps: Step[] = [
  {
    actionType: "changeScene",
    background: "chapters/1/1.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/2.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "showQuiz",
    question: "What is your reply?",
    options: [
      { option: "Sure, I'll come outside", nextRelativeStep: 1 },
      { option: "I'll be there in a minute", nextRelativeStep: 3 },
      { option: "Maybe later", nextRelativeStep: 2 },
    ],
    correctOption: null,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/3.png",
    nextRelativeStep: 2,
    prevRelativeStep: 2,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/4.png",
    nextRelativeStep: 1,
    prevRelativeStep: 3,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/5.png",
    nextRelativeStep: 1,
    prevRelativeStep: 4,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/6.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/7.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/8.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/9.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/10.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/11.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/12.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "showQuiz",
    question: "What do you think?",
    options: [
      { option: "I don't think they could do anything", nextRelativeStep: 2 },
      { option: "The person could access your private chats", nextRelativeStep: 1 },
      { option: "I don't know", nextRelativeStep: 2 },
    ],
    correctOption: 2,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/13.png",
    nextRelativeStep: 2,
    prevRelativeStep: 2,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/14.png",
    nextRelativeStep: 1,
    prevRelativeStep: 3,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/15.png",
    nextRelativeStep: 1,
    prevRelativeStep: 4,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/16.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/17.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/18.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/19.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "showQuiz",
    question: "What do you think?",
    options: [
      { option: "She should go to settings", nextRelativeStep: 1 },
      { option: "I agree with Noah", nextRelativeStep: 2 },
      { option: "I don't know", nextRelativeStep: 2 },
    ],
    correctOption: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/20.png",
    nextRelativeStep: 2,
    prevRelativeStep: 2,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/21.png",
    nextRelativeStep: 1,
    prevRelativeStep: 3,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/22.png",
    nextRelativeStep: 1,
    prevRelativeStep: 4,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/23.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/24.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/25.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/26.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/27.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
  {
    actionType: "changeScene",
    background: "chapters/1/28.png",
    nextRelativeStep: 1,
    prevRelativeStep: 1,
  },
];

export default steps;
